services:
  blog-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./personal_blog:/personal_blog

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
